name: "HON's Wiki"
title: null
description: null
theme: jekyll-theme-minimal

permalink: pretty

readme_index:
    enabled: false
    remove_originals: true

optional_front_matter:
    remove_originals: true

google_analytics: UA-154149655-1
