name: "HON's Wiki"
title: null
description: null

permalink: pretty

readme_index:
    enabled: false
    remove_originals: true

optional_front_matter:
    remove_originals: true

google_analytics_id: UA-154149655-1

theme: jekyll-theme-minimal